name: Generate GitHub Snake

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  generate:
    permissions:
      contents: write

    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Generate snake animation
        uses: Platane/snk@v3
        with:
          github_user_name: Mat-hew-24
          outputs: |
            dist/github-snake.svg
            dist/github-snake-dark.svg?palette=github-dark

      - name: Generate github stats card
        uses: LuciNyan/pixel-profile/action@main
        with:
          outputs: |
            dist/github-stats?username=Mat-hew-24&screen_effect=false&theme=crt&dithering=true
            dist/github-stats-dark?username=Mat-hew-24&theme=crt
          crt_outputs: |
            dist/github-stats-crt?username=Mat-hew-24&include_all_commits=true

      - name: Commit and push snake
        uses: EndBug/add-and-commit@v9
        with:
          message: 'Update profile assets'
          add: 'dist'

      - name: Push stats to output branch
        uses: crazy-max/ghaction-github-pages@v3.1.0
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
